name: Build

on: [push, pull_request]

jobs:
  build_java8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install JDK 1.8
      uses: joschi/setup-jdk@v1.0.0
      with:
        java-version: 'openjdk8'
    - name: Build with Maven
      run: mvn -B clean install -Pproxy -fae

  build_java11:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install JDK 11
        uses: joschi/setup-jdk@v1.0.0
        with:
          java-version: 'openjdk11'
      - name: Build with Maven
        run: mvn -B clean install -Pproxy -fae

  build_java11_no_proxy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install JDK 11
        uses: joschi/setup-jdk@v1.0.0
        with:
          java-version: 'openjdk11'
      - name: Build with Maven
        run: mvn -B clean install -fae

  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install JDK 11
        uses: joschi/setup-jdk@v1.0.0
        with:
          java-version: 'openjdk11'
      - name: Build with Maven
        run: mvn -B clean install -Pproxy -fae

